"""Member details

Revision ID: 39ca714c3c20
Revises: 3299b41d9746
Create Date: 2025-09-12 17:37:50.656363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ca714c3c20'
down_revision = '3299b41d9746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree_program', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('year_or_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('institution', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('institution')
        batch_op.drop_column('year_or_status')
        batch_op.drop_column('degree_program')

    # ### end Alembic commands ###
